import { sqlBoolean, sqlString, sqlUuid } from '../shared/sqlEscapeHelpers';
import type { MappedTeacherRow } from './types';

/** Same bcrypt hash as supabase/seeds/test.sql (password "password"); accounts use magic link later. */
const SEED_ENCRYPTED_PASSWORD = '$2a$10$9e974vMhtRxGA42trytRd.tC0yXzEhsKO0xN8lgoLjy5psvhsJTY.';

export type TeacherSqlRow = MappedTeacherRow & { userId: string };

export function buildTeachersSql(rows: TeacherSqlRow[]): string {
	if (rows.length === 0) {
		return '-- No teachers to import\n';
	}

	const valueTuples = rows
		.map((row) => {
			return `    (${sqlUuid(row.userId)}, ${sqlString(row.email)}, ${sqlString(row.firstName)}, ${sqlString(row.lastName)}, ${sqlString(row.phoneNumber)}, ${sqlString(row.bio)})`;
		})
		.join(',\n');

	const lessonTypeLinks = rows.flatMap((row) =>
		row.lessonTypeNames.map((lessonTypeName) => ({
			userId: row.userId,
			lessonTypeName,
		})),
	);

	const lessonTypeSql =
		lessonTypeLinks.length === 0
			? '  -- No teacher_lesson_types links to insert'
			: `  CREATE TEMP TABLE mongo_import_teacher_lesson_types (
    teacher_id UUID NOT NULL,
    lesson_type_name TEXT NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO mongo_import_teacher_lesson_types (teacher_id, lesson_type_name)
  VALUES
${lessonTypeLinks.map((link) => `    (${sqlUuid(link.userId)}, ${sqlString(link.lessonTypeName)})`).join(',\n')};

  INSERT INTO public.teacher_lesson_types (teacher_user_id, lesson_type_id)
  SELECT m.teacher_id, lt.id
  FROM mongo_import_teacher_lesson_types m
  INNER JOIN public.lesson_types lt ON lt.name = m.lesson_type_name
  ON CONFLICT (teacher_user_id, lesson_type_id) DO NOTHING;`;

	return `-- Generated by import/teachers — apply manually to the target database.
DO $$
BEGIN
  CREATE TEMP TABLE mongo_import_teachers (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    phone_number TEXT,
    bio TEXT
  ) ON COMMIT DROP;

  INSERT INTO mongo_import_teachers (id, email, first_name, last_name, phone_number, bio)
  VALUES
${valueTuples};

  INSERT INTO auth.users (
    id,
    instance_id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  )
  SELECT
    id,
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    email,
    '${SEED_ENCRYPTED_PASSWORD}',
    now(),
    '{"provider":"email","providers":["email"]}',
    json_build_object(
      'first_name', first_name,
      'last_name', last_name
    ),
    now(),
    now(),
    '',
    '',
    '',
    ''
  FROM mongo_import_teachers
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    raw_user_meta_data = EXCLUDED.raw_user_meta_data,
    updated_at = now();

  INSERT INTO auth.identities (
    id,
    user_id,
    provider_id,
    provider,
    identity_data,
    last_sign_in_at,
    created_at,
    updated_at
  )
  SELECT
    id,
    id,
    email,
    'email',
    json_build_object(
      'sub', id::text,
      'email', email,
      'email_verified', true,
      'provider', 'email'
    ),
    now(),
    now(),
    now()
  FROM mongo_import_teachers
  ON CONFLICT (id) DO NOTHING;

  UPDATE public.profiles p
  SET
    first_name = t.first_name,
    last_name = t.last_name,
    phone_number = t.phone_number,
    email = t.email
  FROM mongo_import_teachers t
  WHERE p.user_id = t.id;

  INSERT INTO public.teachers (user_id, bio, is_active)
  SELECT id, bio, ${sqlBoolean(true)}
  FROM mongo_import_teachers
  ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    is_active = EXCLUDED.is_active,
    updated_at = now();

${lessonTypeSql}
END $$;
`;
}
